### ISSUE TITLE
old android calc polyfill?

### ISSUE THREAD

**Issue by Emnalyeriar** [peterramsing/lost#153] opened 2015-07-22 13:17 UTC
Does anyone have an android 4.1 or 4.2 calc polyfill that works with this grid?
I have tried those two:
https://github.com/Eccenux/PolyCalc
https://github.com/closingtag/calc-polyfill
but none of them seems to work with this grid. Is it even possible?
I've tried many diffirent grid and this one is awesome compared to others but I need to support older android borwsers.

**Comment by corysimmons** [comment] 2015-07-22 13:20
Sorry I don't think any of the polyfills work with old Android. What % of users are on old Android anyway?

**Comment by Emnalyeriar** [comment] 2015-07-22 13:32
Based on this:
http://developer.android.com/intl/zh-CN/about/dashboards/index.html
its about 50%. In the company I work we support only 4.4 and up but they said although we don't support it it has to at least have the grid working.

**Comment by corysimmons** [comment] 2015-07-22 13:41
Ah that sucks. You might want to try my other grid, Jeet. It's similar in some ways and doesn't rely on `calc` so it should work for you.

**Comment by Emnalyeriar** [comment] 2015-07-22 13:42
Yeah, I used that previously but now I need to work on fixed margins, can't use %-based margins.

**Comment by corysimmons** [comment] 2015-07-22 13:49
Then you're stuck in a pickle. `calc()` is the only thing that can do fixed margins and percentage columns.

**Comment by corysimmons** [comment] 2015-07-22 13:49
Well, actually Bootstrap and Foundation's grids have fixed "gutters" and percentage columns. Might want to check them out.

**Comment by Emnalyeriar** [comment] 2015-07-23 08:48
Yep, I know those but I really wanted to set my columns in css not with html classes.

**Comment by corysimmons** [comment] 2015-07-23 13:31
You could try something like this http://codepen.io/corysimmons/pen/vOzoRb?editors=110

**Comment by Emnalyeriar** [comment] 2015-07-24 07:59
Thanks for your feedback, I really appreciate it. I was running short on my time for this project so I have decided to use this [http://gridle.org/] (http://gridle.org/). I just hope we'll soon drop support for Android <4.4.

**Comment by corysimmons** [comment] 2015-07-24 13:43
np. I also don't think old Android is 50% of your users. More like 1-3% I'd imagine. It's 6% for all versions of Android browser. http://gs.statcounter.com/#desktop+mobile-browser_version_partially_combined-ww-monthly-201406-201506-bar

**Comment by mi2oon** [comment] 2015-12-05 19:03
@corysimmons Android 4.4 is still quite popular here and the only thing it doesn't support is multiplications and divisions according to caniuse. So, why don't we just do these operations and leave the subtractions and addition to the browser. Not sure if it's possible but just an idea.

**Comment by corysimmons** [comment] 2015-12-05 19:35
Hmm. I'm not sure if it's possible either but it sounds like it's worth exploring. Reopening and would love a PR if anyone wants to tackle this.

**Comment by mi2oon** [comment] 2015-12-06 21:37
@corysimmons I am not sure if this should be handled in lost. But if so we can make an option for the fallback support. As for the support itself it should be fairly easy to handled inside lost. We just need to create two width properties first the fallback secondly the uncalculated one. The second one will be ignored by browsers that doesn't support them.

However, I was thinking since in our team we are using PostCSS I could make a calc fallback support, a PostCSS plugin which can run after lost and also be available for those who just want the fallback in general. But that is probably going to be difficult but not impossible. 
The overall idea is to create a binary expression tree and using the Shunting-Yard algorithm create a custom evaluation infix equation which leaves the addition and subtraction intact.

**Comment by eybarta** [comment] 2015-12-22 08:54
According to the most recent data: http://developer.android.com/about/dashboards/index.html 
the usage percentage of older versions sum up to 33% of Android users.. who make up 9% of total browser usage according to: http://gs.statcounter.com/#mobile+tablet-browser-US-monthly-201412-201511-bar  
That means the general usage for old Androids (in the USA) rounds up to 3%.  
I'm having a hard time deciding if I want to leave out these users from using our application, as I was really looking forward to implementing Lost in our development.
I'd be much happier if there was some kind of built-in fallback of course, I'm probably not savvy enough to hack a good one myself, but if anyone has made progress on one, I'd really appreciate to hear about it :)

**Comment by mi2oon** [comment] 2015-12-22 10:25
@eybarta I am from Denmark and I think we are on 7% but a fallback option would surely be nice. But I think it was 4.4(KitKat) that was the problem and that is fairly new. Anyway, I had an idea but I haven't had much time lately but I do have a vacation coming up. :)

Nevertheless, if anyone else have other ideas or solutions do share.

**Comment by eybarta** [comment] 2015-12-22 11:04
@mi2oon You're right, 4.4 is not supported either.. Now I'm thinking either detecting older versions and popping a message 'Please view in chrome' (Chrome on older Androids don't have this issue right?), or just going with a different solution.. Thinking of Jeet, but worried that maybe the development is halted since Cory moved on to Lost..? Cory?
@Emnalyeriar Are you happy with gridle? it seems pretty robust and gives the option to use mixins rather than many html classes.. Is that the way you use it?

**Comment by eybarta** [comment] 2015-12-22 14:10
It seems old Android browsers do support the old flexbox spec, what ever that means > http://caniuse.com/#feat=flexbox  
Also in the same table it lists a bunch of flexbox issues in ie10-11, have these been tested out with the Lost framework in flex mode?

**Comment by Emnalyeriar** [comment] 2015-12-23 15:07
@eybarta When it comes to gridle me and the team I work with are pretty satisfied with it. We choose it mainly because it fits the grid that our graphic designer uses (its similar to the one that bootstrap has). At first it might seem like there are too many mixins but its easy to learn if you code 1-2 projects with it. I really like how you can define states and then use states mixins instead of media queries.

**Comment by corysimmons** [comment] 2016-01-25 05:33
@eybarta Yeah I stopped working on Jeet a loonnnnnggggg time ago. I actually just gave this repo to @peterramsing who is the new maintainer.

Can someone confirm if [calc-polyfill](https://github.com/closingtag/calc-polyfill) works in old Android? Try a barebones example (e.g. `width: calc(100% / 3);`) just to see if the polyfill is working. If it is, then try it with Lost (our math might be too hairy).

It says it works on Android 4.0.3: https://github.com/closingtag/calc-polyfill#usage

**Comment by corysimmons** [comment] 2016-01-25 07:35
Okay so I did some testing (Android emulation is harder than I thought it'd be) and it seems like calc polyfill works in at least 4.1.1 and up. (I couldn't test below that because Android emulation isn't fun)

Lost _is_ broken in these browsers though.

It seems like they can't interpret `nth-child(n)`...

When I change this to `:nth-child(1n)` everything works as expected.

There's also subpixel rounding errors on old Android that add up. `float: right` on last element in a row might be a good idea.

**Comment by peterramsing** [comment] 2016-01-25 20:49
float: right on the last row is [now added](https://github.com/peterramsing/lost/releases/tag/6.7.0).

**Comment by peterramsing** [comment] 2016-01-25 20:50
The `nth-child(n)` might be something more difficult to solve. Do we just not support it or do we fix it? I'm slightly one for not supporting as that's a ways back but if it's needed...

**Comment by corysimmons** [comment] 2016-01-25 21:34
I just spun up a few more Android VMs.

I can confirm `calc` _and_ `nth-child(n)` **do not work** in Android Browser 4.3 and below.

Regardless of what https://developer.android.com/about/dashboards/index.html says, according to http://caniuse.com/usage-table (based on StatCounter Global Stats) you're looking at excluding **1.66%** of users (who are probably already used to an insanely terrible web browsing experience).

`calc` **is** supported in 4.0.3+ Android Browser with https://github.com/closingtag/calc-polyfill

As project lead, it's up to you if you want to figure out how to get rid of `nth-child(n)` and support those 1.66% of users.

**Comment by peterramsing** [comment] 2016-01-26 00:38
I think that this is a non-issue for this type of grid. Thanks for the legwork @corysimmons

**Comment by corysimmons** [comment] 2016-01-26 02:38
:+1:

**Comment by corysimmons** [comment] 2016-01-26 02:50
@peterramsing Between me and you, I forget why I added `nth-child(n)` in there, but I'm pretty sure it's possible to remove it.

**Comment by corysimmons** [comment] 2016-01-26 03:12
I realized why I added it in. It needs to be there to give it the same specificity as other nth selectors. This is particularly needed around media queries.

Good news though! `1n` accomplishes the exact same thing as `n` except it works in the old Androids.

1 character and you support 1.66% more users. ;)

You might want to do a few visual tests (particularly with multiple media queries affecting the same unit) to ensure this doesn't break anything, but I'm pretty sure it won't.

Lost on Android Browser 4.1.1 (should work all the way down to 4.0.3)

![](https://i.imgur.com/Olm3viY.png)

**Comment by peterramsing** [comment] 2016-01-26 04:47
I think `1n+0` is the better syntax replacement for `n`. Since you have the tests setup, want to double check that works? I should probably also get some simulators setup as well.

**Comment by peterramsing** [comment] 2016-01-26 04:47
From MDN: https://developer.mozilla.org/en-US/docs/Web/CSS/:nth-child

> 1n+0, or simply n, would match every child element.

**Comment by peterramsing** [comment] 2016-01-26 04:49
(and did I forget to mention, good catch?! @corysimmons )

**Comment by corysimmons** [comment] 2016-01-26 04:53
What's the advantage of `1n+0` vs `1n`? `1n` seems more readable and produces less characters.

Thanks. I'm just sorry I didn't figure this out sooner. Poor Android dudes above... :(

**Comment by peterramsing** [comment] 2016-01-26 05:06
@corysimmons I suppose I'm just a rule follower. There _should be_ no difference...but Android thinks there is so following the spec as much as possible makes me more confident in the stability of the solution. That's all.

**Comment by corysimmons** [comment] 2016-01-26 05:29
Go for it. Just updated MDN so in a minute `1n` will be the new convention. Mwahahaahaha!!! :smiling_imp:

**Comment by peterramsing** [comment] 2016-01-26 05:58
@corysimmons Oh you're funny. https://developer.mozilla.org/en-US/docs/Web/CSS/:nth-child$compare?from=997667&to=997679

**Comment by peterramsing** [comment] 2016-01-26 06:04
Addressed in #250

**Closed by peterramsing** 2016-01-26 06:04 UTC
Labels: component: lost-column, component: lost-waffle, resolution: Pull Request, type: Enhancement

**Comment by corysimmons** [comment] 2016-01-26 07:58
:dancers:
