### ISSUE TITLE
Safari (OS X and iOS) nested grid gap appearing

### ISSUE THREAD

**Issue by bradryanbice** [peterramsing/lost#200] opened 2015-12-21 16:57 UTC
I'm only seeing this in Safari (OS X and iOS), but when nesting a grid, I am getting the attached gap at the end of the nested row. Not an issue in Chrome or Firefox on Mac.

HTML:

``` html
    <div class="grid-lost-2 om-grid-display">
        <section>
            <div>1</div>
            <div>2</div>
            <div>3
                <section>
                    <div>1</div>
                    <div>2</div>
                    <div>3</div>
                    <div>4</div>
                </section>
            </div>
        </section>
    </div>
```

SCSS:

``` scss
    .grid-lost {
        & + & {
            margin-top: 3.2rem;
        }
        section {
            lost-center: 1170px; // Max-width, center and clearfix
        }
        div {
            lost-column: 1/4;
            @media all and (min-width: $break1) {
                lost-column: 1/6;
            }
            @media all and (min-width: $break2) {
                lost-column: 1/12;
            }
        }
    }

    .grid-lost-2 {
        @extend .grid-lost;
        & > section > div {
            lost-column: 1/4;
        }
        & > section > div:last-child {
            lost-column: 1/2 3;
        }
        & > section > div > section > div {
            lost-column: 1/4;
        }
    }
```

![screen shot 2015-12-21 at 10 01 05 am](https://cloud.githubusercontent.com/assets/8323556/11934821/f98c6318-a7c9-11e5-9167-75e2388917e0.png)

**Comment by peterramsing** [comment] 2015-12-29 06:24
I'll take a look at this either tomorrow or the next day and see what Safari might be doing differently.

Have you had any updates? If you inspect the elements does it lead to any hints?

Peter

**Comment by corysimmons** [comment] 2015-12-29 07:43
I see this too.

We could possibly fix it by applying a `float: right` to every cycle'd element (so every 3rd element in a `lost-column: 1/3;`). This might cause unexpected results (elements floated right when the author didn't intend for them to be), but I doubt it.

Worth messing around with and testing. A px gap on Safari is pretty rad for a grid that prides itself on being super advance. :^(

**Comment by peterramsing** [comment] 2015-12-30 05:57
@corysimmons @bradryanbice 

I am missing something, I think. I'm unable to get this to replicate. @corysimmons , how are you seeing this?

**Comment by bradryanbice** [comment] 2015-12-30 19:18
Are you looking at this on actual Safari, on a Mac? and on iOS? I can't not make it happen. It's definitely going to prevent my company from using this grid system unless we can find a way around it.

**Comment by peterramsing** [comment] 2015-12-30 20:30
I am looking in actual Safari. I'm actually getting something completely different than your screenshot from your code you put in the issue, so I think I'm missing something.

I'd love to see how Safari inspects that to see what is actually causing it.
Here's what I'm using-would love to see how they compare.
https://github.com/peterramsing/lost-grid-testing/tree/issue/200

![screen shot 2015-12-30 at 12 21 22 pm](https://cloud.githubusercontent.com/assets/3523268/12056914/e63f2c0e-aef0-11e5-9b78-d6354267d3bc.png)

I don't doubt there is an issue, I just can't see it. I'm thinking my markup doesn't match.

**Comment by bradryanbice** [comment] 2015-12-30 20:36
But, the gap is there? I'm seeing a 1-pixel gap in your screenshot after the 4th column in the nested row... exactly what I am getting.

![screen-shot-2015-12-30-at-2 33 46-pm](https://cloud.githubusercontent.com/assets/8323556/12057038/aaebd442-af02-11e5-8d43-e233d30c4eb2.png)

**Comment by peterramsing** [comment] 2015-12-30 20:38
I suppose this is my face palm moment. Sorry! Let me see if I can get to the bottom of if. Yay browsers.

**Comment by peterramsing** [comment] 2015-12-30 20:52
I'll spend some time looking at it tonight. You'll have something from me by tonight.

@corysimmons You're right. A float fixes it just fine but it feels a bit like a hack and there could be unintended consequences. Especially when the issue is only in Safari.

**Comment by peterramsing** [comment] 2015-12-30 21:38
I quickly chatted about this with a colleague and he confirmed that this is a sub-pixel issue. I want to do some reading on it a bit more tonight to ensure that there isn't unintended consequences to adding a float in, but I think this should be solved with a `float: right;` on the last item in the cycle as @corysimmons suggested. If this is standard behavior in other grids then I don't see it causing issues where users's don't understand what's happening. Plus, some documentation can round this out nicely.

I'll finalize this thought process more tonight. Just quick scribbles for now but I need to prep for a meeting and get some more work done before closing out my work day. I'll certainly have something decided on this soon and a roadmap for implementation within the week.

Thanks @bradryanbice for finding this. I'm still getting my head wrapped around this entire project since the repo transfer (#203).

**Comment by peterramsing** [comment] 2015-12-31 03:17
@bradryanbice I've added a very simple `float: right;` but have done minimal real-world testing. You can find it here: https://github.com/peterramsing/lost/tree/add-float-to-last-cycle-div

Want to see if that helps with this issue? I see it solves it for me.

Again, I want to do some more testing. I also think that I'd like to push this to 6.7.x but haven't decided for sure.

![screen shot 2015-12-30 at 7 14 55 pm](https://cloud.githubusercontent.com/assets/3523268/12060688/f778cc4e-af29-11e5-8fef-59a739a3c706.png)

**Comment by corysimmons** [comment] 2015-12-31 21:53
:+1: 

I'd suggest testing this with a variety of sized blocks and cycles and such.

This fix will also need applied to waffle.

**Comment by peterramsing** [comment] 2015-12-31 21:55
@corysimmons Waffle-check. I'll get a PR submitted for this to ensure that a checklist is in place and nothing is missed.

**Comment by corysimmons** [comment] 2015-12-31 21:57
The demo page is a decent way to test stuff too. Anytime I worked on Lost I'd do some random visual tests, and if everything looked right I'd update the code in the gh-pages demo. Sometimes it'd reveal something. It's also a nice way to point at fresh code when someone is looking for some examples.

**Comment by peterramsing** [comment] 2015-12-31 21:58
@corysimmons I did just that last night. :smile: The demo page certainly is helpful. I'm going to also build out some complex layouts for test cases as well.

**Closed as completed** 2016-01-25 04:08 UTC
Labels: type: Bug, type: Enhancement, component: lost-column, resolution: Pull Request
