### ISSUE TITLE
Nested syntax

### ISSUE THREAD

**Issue by geleto** [peterramsing/lost#151] opened 2015-07-09 09:21 UTC
Using a nested syntax like in [PostCSS Nested](https://github.com/postcss/postcss-nested) will allow Lost Grid to be aware of how the elements are positioned in the HTML, which will make some nice features possible:
* Automatic cycle
* Fixed-size elements - discussed [here](https://github.com/corysimmons/lost/issues/142)
* Reordering elements - this is a must have for responsive layouts. Easy with flexbox, not sure if possible with calc?

Here's how it can work.
The HTML:
```HTML
<div id="main">
  <div class="sidebar">sidebar</div>
  <div class="content">
      <div class="content-header">content header</div>
      <div class="content-info">info</div>
  </div>
  <div class="main-column">1</div>
  <div class="main-column">2</div>
</div>
```
The CSS:
```SASS
#main{
  lost-center: 980px;
  lost-order: 1 2 4 3;
  .sidebar{
    lost-column: 20rem;
  }
  .content{
    lost-column: 1/2;
    .content-header{
      lost-row:0.4rem;
    }
    .content-info{
      lost-row:1/1;
    }
  }
  .main-column{
    lost-column: 1/4;
    lost-repeat: 2;
  }
}
```
`lost-order` reorders the elements, in the above sample it swaps the two `.main-column`s.
`lost-repeat` specifies how many consecutive times the element is used in the HTML.
The fractional elements located in the same container with fixed(rem) sized elements use fractions of the remaining space.

**Comment by corysimmons** [comment] 2015-07-18 18:27
Sorry, I'm going to start working on this on the weekends.

> Automatic cycle
Fixed-size elements - discussed here
Reordering elements - this is a must have for responsive layouts. Easy with flexbox, not sure if possible with calc?

Automatic cycle is already in Lost. If you want to override it you can do `lost-cycle: 2`.

I guess what you're proposing is we look at how many values are in `lost-order` for automatic cycling, but how can we know what they want to cycle on? If they use `lost-repeat` it's essentially the same thing as `lost-cycle`. So I don't think I want to change the syntax to `lost-repeat` and since there's no way of knowing what the user wants to cycle on I don't think `lost-order` would help much.

Fixed sized elements might be something worth looking into, but when we do, it'll be in that issue you linked. Please participate in that discussion.

Lost already has re-ordering with https://github.com/corysimmons/lost#lost-move OR you can use Lost in Flexbox mode and actually make use of the `order` property.

Thanks for the ideas though. Let me know if I didn't understand what you were trying to do. =)

**Comment by geleto** [comment] 2015-07-19 19:31
I think that the source of misunderstanding is that you are thinking mostly in therms of same-width columns. Then of course automatic cycle can be calculated, and reordering can be easily done with move.
But what if the columns are of different widths and some of them are fixed-size and some are fractional...

**Automatic cycle:**
The current automatic cycle does not work if the columns are of different widths. With nested syntax - we know how the columns are laid out in the HTML(e.g. the same way as in the CSS). In the sample I gave - inside #main there are 4 columns:
* a fixed-width sidebar column
* a 1/2 content column
* **two** 1/4 columns. (using lost-repeat:**2** to specify that there are **two** similar columns with same widths, but we could just declare them separately)

So the cycle is 4. And because of the nested syntax Lost Grid can know that there are 4 columns inside #main

**Fixed size columns:**
The syntax I proposed in the other post for fixed-width columns - with a lost-group property is not a very elegant one. With nested syntax we know which elements are in the same group and IMO this way the syntax is much more intuitive.

**Reordering:**
The lost-order syntax is IMO more easy than lost-moving columns around, it can still work like lost-move, but because of nested syntax lost-grid can know by how much to shift each column to change the ordering. And as a bonus it can work with fixed-size columns (for which lost-move does not help much, unless it's changed a bit, e.g. lost-move: 1/3 + 20rem)
But this will not help much in the case where reordering is often needed - if responsive layout kicks in for smaller widths and a column becomes 100% width, but it should be ordered differently to the columns it used to share the same row with.

**Comment by corysimmons** [comment] 2015-07-20 06:05
Reopening because I still don't understand it, but will take a proper look at your explanation some other time.

**Comment by geleto** [comment] 2015-07-20 10:27
Thanks!
The basic idea is to duplicate the html structure of the grid in the CSS with [nested syntax](https://github.com/postcss/postcss-nested) so that Lost Grid will be aware of the position of each element in the grid structure - things like what is the parent container, what other elements are in it, how these elements are ordered, etc.

**Comment by peterramsing** [comment] 2016-02-25 16:22
This issue is fairly old and there hasn't been much activity on it. Closing, but please re-open if it still occurs.

**Closed by peterramsing** 2016-02-25 16:22 UTC
Labels: needs: Feedback, needs: More Info, type: Feature

**Comment by corysimmons** [comment] 2016-02-25 16:35
I think I understand what he's asking for, and it's cool because it'd allow things like asymmetrical grids and such, but it would really turn Lost's API inside out.

**Comment by peterramsing** [comment] 2016-02-25 16:46
My gut is saying to focus on what Lost does best and refine and perfect it before adding and revamping the API. I think the current API offers a lot of functionality and so I'm thinking to keep-on-keeping and and fixing and enhancing where we can.

**Comment by corysimmons** [comment] 2016-02-25 17:22
I think that's the right thing to do. I think Lost's bread and butter is how easy/clean it is to spin up basic grids.

**Comment by peterramsing** [comment] 2016-02-25 18:29
I also have been thinking through how many of these complex edge cases are where vanilla css should be used instead of a framework/library.

**Comment by corysimmons** [comment] 2016-02-25 20:26
I think the problem is Lost was made to be really good at nesting blocks in a box. I think everyone is trying to use it to solve every layout problem. I understand that, but without a getter it's gonna be hard to fulfill every fringe case.

**Comment by peterramsing** [comment] 2016-02-26 03:21
:+1:
